service: default
runtime: python37
# We want to specify the entrypoint to be able to optimize
# the number of gunicorn workers.
# See the following link to determine the number of workers
# http://docs.gunicorn.org/en/stable/settings.html#workers
entrypoint: gunicorn -b :$PORT main:app --workers 2 --timeout 600
env: standard
instance_class: B8

basic_scaling:
  max_instances: 1
  idle_timeout: 10m


# handlers element provides a list of URL patterns and descriptions of how they should be handled.
# https://cloud.google.com/appengine/docs/standard/python/config/appref#handlers_element
handlers:
- url: /
  # script field for handler '/' must be set to 'auto' for runtime python37.
  script: auto
  # Requests for a URL that match this handler that do not use HTTPS are
  # automatically redirected to the HTTPS URL with the same path.
  secure: always
